consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: application-tracker
    version: 1.0.0
paths:
    /health:
        get:
            summary: Health Check
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                default:
                    description: Server Error
                    schema:
                        properties:
                            code:
                                type: integer
                            message:
                                type: string
                                example: error
                        type: object
            security: []
            description: Check if the App is Running
            tags:
                - health
definitions:
    principal:
        type: object
        properties:
            email:
                type: string
            expired_at:
                type: string
            user_id:
                type: number
                format: uint64
securityDefinitions:
    key:
        type: apiKey
        name: Authorization
        in: header
