consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Golang Template
    version: 1.0.0
paths:
    /v1/profile:
        get:
            summary: Find My User Data
            operationId: findMyUserData
            responses:
                "200":
                    description: Success fetch data
                    schema:
                        $ref: '#/definitions/myUserData'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
            description: Find my user data
            tags:
                - user
    /v1/register:
        post:
            summary: Register
            operationId: register
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/registerParamsBody'
            responses:
                "200":
                    description: Success register
                    schema:
                        $ref: '#/definitions/successRegister'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security: []
            description: Register user
            tags:
                - authentication
    /health:
        get:
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security: []
    /v1/login:
        post:
            parameters:
                - in: body
                  schema:
                    $ref: '#/definitions/loginParamsBody'
                  name: data
            responses:
                "201":
                    description: Success login
                    schema:
                        $ref: '#/definitions/successLogin'
                    headers:
                        token:
                            type: string
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Login
            tags:
                - authentication
            summary: Login
            operationId: login
definitions:
    customFields:
        type: object
        additionalProperties:
            type: object
        x-go-package: time
    registerParamsBody:
        x-go-gen-location: operations
        type: object
        required:
            - username
            - password
        properties:
            password:
                type: string
                minLength: !!float 8
            username:
                type: string
    success:
        type: object
        properties:
            message:
                type: string
    successLogin:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successLoginAllOf1'
    successLoginAllOf1:
        properties:
            expired_at:
                type: string
        x-go-gen-location: models
        type: object
    successRegisterAllOf1:
        type: object
        properties:
            user_id:
                format: uint64
                type: number
        x-go-gen-location: models
    error:
        properties:
            message:
                type: string
                example: error
            code:
                type: integer
        type: object
    myUserData:
        properties:
            note:
                $ref: '#/definitions/customFields'
            username:
                type: string
                x-omitempty: false
        type: object
    successRegister:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successRegisterAllOf1'
    loginParamsBody:
        type: object
        required:
            - username
            - password
        properties:
            password:
                type: string
            username:
                type: string
        x-go-gen-location: operations
    modelTrackTime:
        type: object
        properties:
            updated_at:
                x-nullable: true
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
            created_at:
                x-nullable: true
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
            deleted_at:
                format: date-time
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
                x-omitempty: false
                type: string
    user:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/userData'
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    principal:
        type: object
        properties:
            expired_at:
                type: string
                format: date-time
            user_id:
                format: uint64
                type: number
            username:
                type: string
    userData:
        type: object
        properties:
            password:
                type: string
                x-omitempty: false
            username:
                type: string
                x-omitempty: false
            note:
                $ref: '#/definitions/customFields'
securityDefinitions:
    authorization:
        in: header
        type: apiKey
        name: Authorization
